import Head from 'next/head'
import Navbar from './Navbar'

const Layout = ({ children }: any) => {
  return (
    <>
      <Navbar />
      <Head>
        <title>Nilswg MeetUp Room</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-gray-900">{children}</main>
    </>
  )
}

export default Layout
