import Head from 'next/head'
import BlackScreen from './BlackScreen'
import Navbar from './Navbar'

const Layout = ({ children }: any) => {
  return (
    <div>
      <Navbar />
      <Head>
        <title>Nilswg MeetUp Room</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
      <BlackScreen />
    </div>
  )
}

export default Layout
